runtime: nodejs14
service: default

# The following env variables may contain sensitive information that grants
# anyone access to your database. Do not add this file to your source control.
env_variables:
  DB_USER: postgres
  DB_PASS: Postgres!101
  DB_NAME: postgres2
  SECRET: thisisasecret
  # e.g. my-awesome-project:us-central1:my-cloud-sql-instance
  INSTANCE_CONNECTION_NAME: issue-tracker-kp:us-west1:issue-tracker-db

beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: issue-tracker-kp:us-west1:issue-tracker-db